image: python:3.6.8
options:
  docker: true

definitions:
  services:
    java:
      image: openjdk:8

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip3 install -r requirements.txt
    - step:
        image: java:8
        script:
          - bash ./run.sh