image: python:3.6.8

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip3 install -r requirements.txt
          - pip3 install git+https://github.com/allure-framework/allure-python2.git@master#subdirectory=allure-python-commons
          - pip3 install git+https://github.com/allure-framework/allure-python2.git@master#subdirectory=allure-pytest
          - pytest tests