image: python:3.6.8
options:
  docker: true

definitions:
  services:
    java:
      image: openjdk:8

pipelines:
  default:
    - step:
        image: java:8
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip3 install -r requirements.txt
          - bash ./run.sh