image: python:3.6.8
options:
  docker: true

definitions:
  services:
    java:
      image: openjdk:8

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - pip3 install -r requirements.txt
          - apt-get update && sudo apt-get install -y openjdk-8-jdk
          - bash ./run.sh