image: python:3.6.8

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip3 install -r requirements.txt
          - pytest tests