image: python:3.6.8
options:
  docker: true

definitions:
  services:
    java:
      image: openjdk:8

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip3 install -r requirements.txt
          - apt-get update && apt-get install openjdk-8-jdk
          - bash ./run.sh